### ISSUE TITLE
File upload and download

### ISSUE THREAD

**Issue by papuuk** [wooey/Wooey#105]
I wrote this simple script to test file upload and download possibilities. But I don't see any option like that:

````python

import argparse 
import sys

p=argparse.ArgumentParser()

p.add_argument('ifile',help='input_file')
p.add_argument('ofile',help='output_file')

def main():
	a=p.parse_args()
	with open(a.ifile, 'r') as f1:
		i=f1.read()	
	with open(a.ofile, 'w') as f2:
		f2.write(i)
 
if __name__ == "__main__":
    sys.exit(main())

````

**Comment by Chris7** [comment]
Hey @papuuk. For file based arguments (for uploads), you'll need to use the argparse syntax for handling files. That is:

p.add_argument('ifile',help='input_file', type=argparse.FileType('r'))
