### ISSUE TITLE
Script stuck in 'waiting' status

### ISSUE THREAD

**Issue by yoavram** [wooey/Wooey#107]
I run the simple scripts from the docs (http://wooey.readthedocs.org/en/latest/scripts.html#script-guidelines) or my own (since the docs one has no real output, fixed in #109):
```py
import argparse
import sys

parser = argparse.ArgumentParser(description="Find the sum of all the numbers below a number.")
parser.add_argument('--below', help='The number to find the sum of numbers below.', type=int, default=1000)
def main():
    args = parser.parse_args()
    s = sum((i for i in range(args.below)))
    with open('output', 'w') as f:
    	f.write(s)
    return 0

if __name__ == "__main__":    
    sys.exit(main())
```

but the job is stuck as 'waiting', with no output to console-in-browser, and no errors to server console. 
Win7 64bit, python 3.4.3, latest wooey (installed from github master branch), django 1.8. I basically followed the tutorial in the docs.

**Comment by Chris7** [comment]
Do you have the celery server running?

**Comment by yoavram** [comment]
Right, I missed that, sorry.
I run `python manage.py celery worker -c 1 --beat -l info` and get:
```
D:\Anaconda3\envs\wooey\lib\site-packages\django\core\management\base.py:259: RemovedInDjango19Warning: "requires_model_validation" is deprecated in favor of "requires_system_checks".
  RemovedInDjango19Warning)

-B option does not work on Windows.  Please run celery beat as a separate service.
```
Sorry, I don't have time to debug this now, but if you suggest a solution I'll try it in <24 hrs.

**Comment by Chris7** [comment]
You need to remove the --beat argument because windows doesn't support it.

**Comment by yoavram** [comment]
Great!
That should probably be fixed in the docs, so I'm leaving this open to be closed on your judgement.
