### ISSUE TITLE
multiple files

### ISSUE THREAD

**Issue by kobolddoido** [wooey/Wooey#11]
hello! 
Can i choose an unlimited number of files using some like:

parser.add_argument('file', type=argparse.FileType('r'), nargs='+')

Thanks for help

**Comment by Chris7** [comment]
You are unable to do this, but it is a feature within the merge of djangui and wooey. You can preview it here:

https://github.com/wooey/django-djangui/pull/11

**Comment by Chris7** [comment]
This has been merged in with wooey/django-djangui#11 and will be available once the merger is complete.
