### ISSUE TITLE
Default values for arguments

### ISSUE THREAD

**Issue by oinbar** [wooey/Wooey#119]
when defining an argument like so:
parser.add_argument('--below', help='The number to find the sum of numbers below.', type=int, default=1000)

I would expect the UI to load the default value into the textbox, but thats not happening. Is this a bug or is there a particular way of defining default values to work in this manner?

Let me also say, this project is amazing!

**Comment by Chris7** [comment]
I'd call it more of a case we have not defined yet. I'd be open to a PR adding in this using the default as a placeholder. That way the default is shown still but not explicitly passed.

**Comment by oinbar** [comment]
I can get started on it. Im not much of a web dev however (also never used django). where are the views generated?

**Comment by Chris7** [comment]
I'll handle this one. It goes between the clinto->wooey interface so it's probably easiest for me.

**Comment by Chris7** [comment]
Fixed in #122
