### ISSUE TITLE
A couple of Python 2/3 compatability issues

### ISSUE THREAD

**Issue by brian-bk** [wooey/Wooey#123]
Hi, I ran into a couple of easy to solve errors related to differences between python 2 and 3 in `wooey/templatetags/wooey_tags.py`. I was running it with python3.5. But it's a couple of very easy fixes.

In line 168 of , the md5 requires bytes which breaks python 3 compatability. I got a type error that md5 requires a byte rather than a str. A possible solution is just by changing `hashlib.md5(email.lower())` to `hashlib.md5(email.lower().encode())`.

Also, I got an import error since urlencode is in a different location for each python2/3. In 2 it's urllib.urlencode, but in 3 it's urllib.parse.urlencode. Since line 169 is the only time urllib is currently used in wooey_tags.py, you could change the import of urllib to
```
import sys
if (sys.version_info < (3,0)):
  from urllib import urlencode
else:
  from urllib.parse import urlencode
```
and then just call `urlencode`.

**Comment by Chris7** [comment]
Thanks for the report. I'm surprised these haven't been reported yet.

**Comment by brian-bk** [comment]
Just installed the new version, it should be encode() rather than decode(). encode() goes to bytes, and decode() goes to unicode.

**Comment by Chris7** [comment]
If you test/submit a PR I'll merge it in. Otherwise, give me a day or so.
