### ISSUE TITLE
wanna to use version 0.0.4

### ISSUE THREAD

**Issue by hanbeibei** [wooey/Wooey#133]
Hay, 

we are trying to use version 0.0.4, which is much simpler than the django version, Could you tell me where I can get this version's document?

Great appreciate
BB

**Comment by mfitzp** [comment]
Hi @hanbeibei 

The v0.0.4 (based on Flask) is tagged here https://github.com/wooey/Wooey/tree/v0.0.4

However, bear in the mind that version is no longer being developed.

It would be great if you could let us know what it is about v0.0.4 that you prefer — e.g. you say it is *simpler*, are you having trouble setting up the new version? — as it would obviously be better if we could make the latest, actively developed, version meet your requirements.

**Comment by hanbeibei** [comment]
Thanks @mfitzp ,

the reason we are using the 0.0.4 version is that it's much simpler, flask is much simpler than django and less dependencies, there are some other function which will not be using for us, like celery, 

we are working on a highly strict environment, pip can not be used, we had to download all dependencies manually and install them one by one. that's really painful, due to 3rd party module conflict, we can only see the python.exe crash...

we want a fast development and fast deploy web environment, this version 0.0.4 is perfect for us, the problem which we had to face is that we don't know where we can get the document like the latest version.

Thanks again for your kindly reply.
BB

**Comment by hanbeibei** [comment]
the version 0.0.4 had installed and there are no conflict, we can load it from idle

**Comment by Chris7** [comment]
You can always run your own pypi server and use pip with that.

**Comment by hanbeibei** [comment]
Okay

Thanks @Chris7, this issue can be closed
