### ISSUE TITLE
Editing views/styles

### ISSUE THREAD

**Issue by oinbar** [wooey/Wooey#139]
This isn't so much an issue, more a product of my django n00bishness.
I am trying to edit the views and add my own styles to the front page /scripts page ("Wooey" is great, but I would like to use a relevant name for example, perhaps a logo as well, etc). Unfortunately I don't understand the django model, and can't find views/templates or any css files.
Could someone point me in the right direction?
Thanks.

**Comment by Chris7** [comment]
For this, you definitely need more experience with Django. To start with, I'd go through their tutorial polls app (at least the template part). In short, you want to make the following folder structure:

```
project_name/
 project_name/
  templates/
   wooey/

```
and override template names that are found here (the ones you want to replace):
https://github.com/wooey/Wooey/tree/master/wooey/templates/wooey
