### ISSUE TITLE
pip3 install using incompatible dependencies

### ISSUE THREAD

**Issue by eric11** [wooey/Wooey#160]
I was having trouble getting this set up under ubuntu 16.04. The following:
- apt-get update && sudo apt-get upgrade
- apt-get install python3 python3-pip
- pip3 install virtualenv
- virtualenv venv
- source venv/bin/activate
- pip3 install wooey
- wooify -p wapp

Produces: 

Traceback (most recent call last):
  File "/root/venv/lib/python3.5/site-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'kombu.transport' has no attribute 'django'

To get things working I had to pip3 install "kombu<4" and "celery<4.0"

**Comment by Chris7** [comment]
Thanks @eric11. I need to pin EVERYTHING I guess in my reqs -- I thought I could trust celery :)

**Comment by Chris7** [comment]
Ok, this is a problem with django-celery. They have addressed this, but need to push their latest release to enforce celery <= 4.0. This is referenced here https://github.com/celery/django-celery/issues/493

**Comment by Chris7** [comment]
Fixed in latest pypi. Sorry for the delay.
