### ISSUE TITLE
Problems updating scripts

### ISSUE THREAD

**Issue by jschultz** [wooey/Wooey#163]
Hello,

I have seen a variety of problems appear with the arguments following an update of a script. Sorry for the vagueness of these descriptions, but I've found it hard to replicate the problem in a reliable way, although I'd say that at least one of the symptoms below appears more often than not:

1. Repeated 'Optional Arguments' tabs on the script launch page. This isn't too bad as the script still seems to work.
2. Missing tabs (I've seen missing 'Required' and 'Positional' tabs).
3. Some of the arguments missing, ie instead of ~10 optional arguments I only see around 3.
4. Suppressed arguments don't get suppressed, but appear with the help text '==SUPPRESS=='

This seems to happen whether I update the script via the web interface or the GUI. One curious thing that seems to make a difference is to use the GUI to delete all prior versions of a script.

As far as any peculiarities of my setup that might be making a difference go, I am using a non-default script group, and my scripts all contain all three of required, optional and positional arguments.

Many thanks for any assistance!

**Comment by Chris7** [comment]
Hi @jschultz,

Could you please send me an example script that illustrates these problems and provide the output of `pip freeze`?

**Comment by jschultz** [comment]
Thanks for the reply. Here are links to a script and the output from pip freeze:
[RQDA2NVPX.py](https://github.com/BarraQDA/nvivotools/blob/master/RQDA2NVPX.py)
[pip-freeze.txt](https://github.com/wooey/Wooey/files/623454/pip-freeze.txt)

**Comment by Chris7** [comment]
So I looked at it and a few notes -- somethings that could use some sprucing up in the documentation:

For point 3): To suppress arguments, the use of argparse.SUPPRESS is there to hide the argparse related arguments. If you want to suppress these in Wooey, you need to do so through the admin interface (admin/wooey/scriptparameter/) where there is a 'hidden' checkbox (or do what argparse does, and set SUPPRESS to the default argument).

For point 1) -- this is definitely a bug and thanks for sending me your script -- it reproduces easily and I put in a fix.

For point 2/3 -- could I get a screen shot? I have never encountered this.

**Comment by jschultz** [comment]
OK after a little experimentation I've managed to replicate 3 - hoping this is sufficient. If I begin with the same script I linked to before [RQDA2NVPX.py](https://github.com/BarraQDA/nvivotools/blob/master/RQDA2NVPX.py), add it using the command line:

> ./manage.py addscript ~/src/nvivotools/RQDA2NVPX_copy.py

then go and add a new argument in the script before the existing arguments, for instance:

> parser.add_argument('-bo', '--bogus', type=int, default=1)

then update the script:

> ./manage.py addscript --update ~/src/nvivotools/RQDA2NVPX_copy.py

From the script browser I now see (notice only one optional argument):

![screenshot_20161206_155102](https://cloud.githubusercontent.com/assets/218830/20913425/e41c5df0-bbcb-11e6-82ca-ad909a971818.png)

**Comment by Chris7** [comment]
Thank you, I'm busy for the next few days but hope to get this fixed and in a pypi release soon.

**Comment by Chris7** [comment]
I believe these are all resolved on latest master.

**Comment by Chris7** [comment]
Fixed in latest release

**Comment by jschultz** [comment]
Many thanks. For the record, could you outline the procedure to install the update on a running wooey installation. That is, do I need to re-bootstrap and if so, can the installed scripts be migrated to the new instance, or can the update be applied in situ?

**Comment by Chris7** [comment]
You would do this:
1) Upgrade the version of wooey installed via `pip`
2) Since this update actually changed `wooey_settings.py`, you would need to update this by changing `wooey_settings.py` in your project to:
```
