### ISSUE TITLE
Can not execute the task when I add TEMPLATES.DIRS 

### ISSUE THREAD

**Issue by zjhzxjm** [wooey/Wooey#165]
I want to custom the templates, so I add the string "os.path.join(BASE_DIR, 'templates')," into the DIRS list of settings.TEMPLATES, then I copy the templates directory to my project. I can custom the templates successfully, but get the following errors when I execute the task:
10:54:49 web.1    | Internal Server Error: /scripts/violinplot/
10:54:49 web.1    | Traceback (most recent call last):
10:54:49 web.1    |   File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/utils/datastructures.py", line 83, in __getitem__
10:54:49 web.1    |     list_ = super(MultiValueDict, self).__getitem__(key)
10:54:49 web.1    | KeyError: 'wooey_type'
10:54:49 web.1    | 
10:54:49 web.1    | During handling of the above exception, another exception occurred:
10:54:49 web.1    | 
10:54:49 web.1    | Traceback (most recent call last):
10:54:49 web.1    |   File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
10:54:49 web.1    |     response = self.process_exception_by_middleware(e, request)
10:54:49 web.1    |   File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
10:54:49 web.1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
10:54:49 web.1    |   File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
10:54:49 web.1    |     return self.dispatch(request, *args, **kwargs)
10:54:49 web.1    |   File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
10:54:49 web.1    |     return handler(request, *args, **kwargs)
10:54:49 web.1    |   File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/wooey/views/views.py", line 160, in post
10:54:49 web.1    |     data = super(WooeyScriptView, self).post(*args, **kwargs)
10:54:49 web.1    |   File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/wooey/views/views.py", line 91, in post
10:54:49 web.1    |     form = utils.get_master_form(pk=post['wooey_type'])
10:54:49 web.1    |   File "/home/xujm/soft/Anaconda/anaconda3/envs/wooey/lib/python3.5/site-packages/django/utils/datastructures.py", line 85, in __getitem__
10:54:49 web.1    |     raise MultiValueDictKeyError(repr(key))
10:54:49 web.1    | django.utils.datastructures.MultiValueDictKeyError: "'wooey_type'"

**Comment by Chris7** [comment]
How are you overriding the form template? It seems odd that `wooey_type` would be missing since that is defined by the form factory that the template renders.

**Comment by zjhzxjm** [comment]
Firstly, I copy 'wooey/templates' to 'realcloud/realcloud/templates'. 'realcloud' is my project name
Secondly, I modify the code of django_setting.py in my project as follows:
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
...

The problems will go after I removed the value of DIRS

**Comment by Chris7** [comment]
Just to clarify so I can replicate this -- your final folder structure looks like:

`realcloud/realcloud/templates/wooey/xxx.html`?

**Comment by Chris7** [comment]
Hi @zjhzxjm,

These are the steps I followed:

1) Make a new project with wooify
2) Copy `wooey/templates/wooey` to `realcloud/realcloud/templates/wooey`
3) Add `os.path.join(BASE_DIR, 'templates')` to `DIRS` under `TEMPLATES`
4) Edit the script form submission: `templates/wooey/scripts/script_view.html`
5) Everything works.

Let me know if anything deviates from yours, or you can provide the contents of your updated `script_view.html` and I can see what is wrong.

Chris

**Comment by zjhzxjm** [comment]
Thanks for your reply @Chris7

I do the same steps as you said. When I finished the first 3 steps, the problem will come out for executing a task.

**Comment by Chris7** [comment]
By executing a task -- do you mean running a script? Or the execution in celery?

**Comment by zjhzxjm** [comment]
I run the wooey through a procfile, and run a script by website script page

**Comment by Chris7** [comment]
Ok -- without seeing your template `script_view.html`, I don't think I can debug what is breaking since my attempts to replicate your setup led to a functional site.

**Comment by zjhzxjm** [comment]
I have not modified the script_view.html

**Comment by Chris7** [comment]
Ok, can you zip your templates and send them? You can email them if they shouldn't be public. The error indicates that `script_view.html` is not passing the `wooey_type` variable -- but if you have not modified that script I'm not sure why it's happening.

**Comment by zjhzxjm** [comment]
[templates.tar.gz](https://github.com/wooey/Wooey/files/660189/templates.tar.gz)

**Comment by Chris7** [comment]
Awesome @zjhzxjm ! It fails for me now. I'll investigate why this happened.

**Comment by Chris7** [comment]
Ah -- I found it. 

It's failing because `script_view.html` is from an older version of wooey. The line here is missing from your `script_view.html` template: 

https://github.com/wooey/Wooey/blame/master/wooey/templates/wooey/scripts/script_view.html#L33

You should update with the latest templates from wooey (or use an approach like extending the wooey templates and overriding the logic you want to customize).

**Comment by zjhzxjm** [comment]
Thank you very much. I am sorry to bring trouble to you.
