### ISSUE TITLE
 browser images in windows

### ISSUE THREAD

**Issue by Cd48** [wooey/Wooey#17]
To support images when running Wooey under windows, please change

        if ext in ['.png', '.jpg', '.jpeg', '.tif', '.tiff']:
            with open(filename, 'r') as f:

in wooey/public/views.py to

        if ext in ['.png', '.jpg', '.jpeg', '.tif', '.tiff']:
            with open(filename, 'rb') as f:

this should not make a difference for unix environments

**Comment by mfitzp** [comment]
@Cd48 Thanks for the bug report much appreciated. We'll shortly be merging djangui into this repo (a new implementation of Wooey based on Django) and this bug will be fixed once that is complete.

**Comment by mfitzp** [comment]
@Cd48 This is now fixed in the merged version of Wooey (now based on django). If you re-install from this repository it should work fine on Windows. A release via PyPi (for `pip`) will follow shortly.
