### ISSUE TITLE
Dynamic argument that depends on the contents of a folder.

### ISSUE THREAD

**Issue by haricot** [wooey/Wooey#176]
Hello,
I try to list the contents present in a folder and to pass this list in argument choices, it works but while i add a new file in the folder it does not appear in the field.
Would there be way to reboot the script just before the forms start?

Thank you!
```
#-*- coding: utf-8 -*-
import os
import argparse

list_folder = [f for f in os.listdir("/tmp/test" )]
parser = argparse.ArgumentParser(description="list folder")
parser.add_argument('--folder_lists', type=str , choices=list_folder)
  
def main():
   args = parser.parse_args()
  
if __name__ == "__main__":
    sys.exit(main())
```

**Comment by haricot** [comment]
Or do a script that will update the specific field with "Script parameter" via "Djcelery Periodic Tasks" but it seems a bit excessive.
This may be another issue tagged future but I do not know too much.
Otherwise I can do without more it's less convenient.

**Comment by haricot** [comment]
After reflection, there is everything needed to make it work with celery and inotify (celery.worker.autoreload), although I do otherwise for now.

**Comment by Chris7** [comment]
Glad you resolved this!
