### ISSUE TITLE
where can I specify the executable for scripts when not using celery

### ISSUE THREAD

**Issue by lordzappo** [wooey/Wooey#179]
It seems to be assuming the thing hosting the webprocess should also do the execution if we dont use celery, which is not the case for me with uwsgi:

![image](https://cloud.githubusercontent.com/assets/1440762/24748218/05b19e2e-1a8d-11e7-9cd7-183529635e66.png)

**Comment by lordzappo** [comment]
I have a full nginx uwsgi config for this, now, if you guys want to add to your tutorials for those not interested in honcho.

**Comment by Chris7** [comment]
I would love to add that @lordzappo.
