### ISSUE TITLE
Subparser support

### ISSUE THREAD

**Issue by elehcim** [wooey/Wooey#181]
I have a program structured into subcommands, like the example below:
```
$ my_script --help
usage: my_script [-h] [-v {0..4}] [--debug] [-p] {offline,online,user} ...

My script

optional arguments:
  -h, --help            show this help message and exit
  -v {0..4}, --verbosity {0..4}
                        set verbosity
  --debug               Enable debug mode
  -p, --parallel        Enable parallel processing

Subcommands:
  {offline,online,user}
```
```
$ my_script user --help
usage: my_script user [-h] -c CONF_FILENAME [--opt1 OPT1] [--opt2 OPT2]

optional arguments:
  -h, --help            show this help message and exit
  -c CONF_FILENAME, --conf CONF_FILENAME
                        Configuration file
  --opt1 OPT1           Option1
  --opt2 OPT2           Option2
```

Are you planning to include subparsers into Woeey? Is there any workaround to be able to use the above script with the subcommand `my_script user` with woeey?
Thank you for the very nice app

**Comment by Chris7** [comment]
Subparser support needs to be implemented first in the library [clinto](https://github.com/wooey/clinto) we use to convert command line scripts to some UI markup. Then some changes to wooey will have to be done to give an intuitive interface. This is a long outstanding issue, https://github.com/wooey/clinto/issues/2, and something that we hope to get in one day. Of course, PRs are more than welcome :)

**Comment by Chris7** [comment]
@elehcim The master branch has support for subparsers (for argparse). It needs some more testing but should be in the next release.
