### ISSUE TITLE
Manage continuously running scripts

### ISSUE THREAD

**Issue by bernhardmostrey** [wooey/Wooey#187]
I would like to use this interface to manage continuously running python scripts.
I managed to get everything running but I cannot add my scripts because they just keep running.
The addscript command cannot finish adding the script.

Any solution for this?

**Comment by SSchott** [comment]
You should check the output of the addscript command. Usually it's either a module which is not globally available or you haven't defined the argparse commands correctly.

**Comment by Chris7** [comment]
Hi @bernhardmostrey,

This is because Wooey loads the script to introspect argparse (or docopt, etc). You likely are not using the convention of:
```
if __name__ == '__main__':
  ..run your script
```

So essentially -- check that the script is being executed as a script. Let me know if you have any other problems.

**Comment by Chris7** [comment]
Closing as I assume this is resolved. Let me know if otherwise.
