### ISSUE TITLE
tar.gz file size is incorrectly reported

### ISSUE THREAD

**Issue by pymenow** [wooey/Wooey#202]
tar.gz file size is incorrectly reported. The .zip files of the reports are correctly reported though.
On wooey-0.9.10 + Ubuntu 16.04 Lts + Anaconda3 - 5.01

**Comment by pymenow** [comment]
Also adding :
Zip files dont maintain the same folder structure and all files are zipped in the root. Which causes files to be overwritten when unzipped. 
tar.gz files however maintain the folder structure when compressing the output files and this is ideal.

**Comment by Chris7** [comment]
Can you provide a screenshot? I just made a test for this and the filesize is correct on my system (linux). I'll look into the second issue (thanks for reporting them!)

**Comment by pymenow** [comment]
Here is the screen shot : 
![screenshot from 2017-12-22 10-37-25](https://user-images.githubusercontent.com/34679063/34286089-75a30c6a-e704-11e7-8249-605b695f8e53.png)

The actual size of the file is 30MB, the zip file shows correctly. Probably the sub folder file size is not taken into consideration ?

**Comment by Chris7** [comment]
The zip and tar file should not be the same size. What does the command line indicate for the file sizes?

**Comment by pymenow** [comment]
Thanks for the quick fix on the zip files over writing! Regarding the file size , when i actually check the file size on the system via du -h its shows exactly what the UI reports, now I am wondering what could cause that ! Because when i do download the tgz file its actually much larger than reported file size and comparable to the zip file size !

**Comment by Chris7** [comment]
I figured it out. It's because the tar file is being un-gzipped by your browser on the download. This is because the static assets are being served by Django's runserver I imagine in your setup. If static assets are handled by nginx or whitenoise, this should not occur.

**Comment by pymenow** [comment]
Thanks will move to nginx for production!
