### ISSUE TITLE
Lists using argparse

### ISSUE THREAD

**Issue by pymenow** [wooey/Wooey#207]
```
parser.add_argument(
    '-ml', '--mzlist',
    default=['14', '16', '18', '20', '28', '32', '40'],
    nargs='+',
    help='A list to analyze ',
    required=False)
```

The above code works fine on a standalone / cmdline system . Where user inputs spaced apart are taken in as a single list
EG : -ml 2 34 56 2
ml = ['2', '34', '56', '2']

However this doesnt work in wooey.

**Comment by Chris7** [comment]
Thanks, this is because default values were not being serialized properly. I have a fix for it, but it may time a little time until the official release. There is a fair bit of testing I need to do for the new subparsers. If that takes a longer than expected time, I might do another patch release.

**Comment by pymenow** [comment]
i have overcome this by using a str and then splitting it in my code.
However a list if always useful . Please let me know if I can help test it

**Comment by Chris7** [comment]
It is now in master, you can test it by installing the latest from there.

**Comment by pymenow** [comment]
@Chris7 testing in master has been going on well. PLanning to open this up to a larger audiance in the company, wondering when the next release is targeting as I am concerned about losing the database once we go wide.

**Comment by Chris7** [comment]
I put in a considerable number of changes with how scripts are uploaded to avoid duplicates (they now have a checksum) and the subparsers. I want to add in support for the latest versions of celery & Django, and then I think a release will be coming. I'm not sure on the timeline, but probably a few weeks.
