### ISSUE TITLE
Stale tasks in wooey web interface

### ISSUE THREAD

**Issue by PheonixS** [wooey/Wooey#210]
After restart Wooey! tasks present in web interface but not in celery. Cannot stop, remove or delete this tasks.
python manage.py celery events
showing empty lists
wooey==0.9.8
How can I stop it? :)

**Comment by Chris7** [comment]
Thanks for the report @PheonixS. It's definitely something that was overlooked. For the time being, you could remove these from the admin page.

**Comment by Chris7** [comment]
This has been fixed in the latest master. Thanks for reporting it!
