### ISSUE TITLE
How to define file upload parameters?

### ISSUE THREAD

**Issue by luisdelatorre012** [wooey/Wooey#213]
I'm new to Wooey and want to create a UI for a program that requires an input file from the user. How do I define a parameter like this? I didn't see anything about this in the documentation, but I may have missed it.

(For example, http://wooey.barraqda.org/scripts/normalisenvpx/ has a file upload button).

**Comment by Chris7** [comment]
Hi @luisdelatorre012,

You simply follow the conventions of argparse and it will give the user an upload file. For instance:
`parser.add_argument('--image', help='The image to crop', type=argparse.FileType('r'), required=True)`

**Comment by luisdelatorre012** [comment]
Got it. Thanks for the quick answer.
