### ISSUE TITLE
WOOEY_REALTIME_CACHE is not work for me

### ISSUE THREAD

**Issue by abicorios** [wooey/Wooey#220]
Please, show working example of useing it. How must I set my settings for the realtime update of the script output? I see only one result after end of my script.

**Comment by Chris7** [comment]
Do you have a cache in place like redis for Django, such as this setup: https://docs.djangoproject.com/en/2.0/topics/cache/#memcached? If so, whatever cache you have, set `WOOEY_REALTIME_CACHE` to.

**Comment by abicorios** [comment]
I am not experienced in Django. I use Wooey as the selfcomplited product. So I do:
`pip install wooey
wooify -p myproject`
Then I run my script from Wooey, it is not realtime. So I read WOOEY_REALTIME_CACHE in http://wooey.readthedocs.io/en/latest/configuration.html And I do not see the path of the setting file in which I can specify WOOEY_REALTIME_CACHE , and I do not see the value which I need specify WOOEY_REALTIME_CACHE. When I reed https://docs.djangoproject.com/en/2.0/topics/cache/#memcached, I do not see the path of the setting file too. So, realy, it is nice to add in the documentation the path of the setting file in which I can specify WOOEY_REALTIME_CACHE and value which I need specify. Also, the realtime by default is nice. If tou do not want such default, so you can create the simple on/off option in the simple setting file, and describe it in the documentation. As far as your realtime is nice for Django developers, but I am a Wooey user and I cannot use this realtime.

**Comment by Chris7** [comment]
I updated the `wooify` script in the upcoming version to setup a cache backend as the database for simple demo apps.

**Comment by abicorios** [comment]
It is nice commit. I need it. But it is not work for me, because an infinite waiting in Linux and Windows.
From home dir:
```
git clone https://github.com/abicorios/slowPrint
conda create -n woo python=3
. activate woo
pip install git+https://github.com/wooey/Wooey@master
wooify -p myproject
cd myproject
./manage.py addscript ~/slowPrint/a.py
./manage.py runserver
```
Where conda is obtained from https://conda.io/miniconda.html

**Comment by Chris7** [comment]
You may be running into buffered stdout. Can you try running python in unbuffered mode or flushing the stdout in your script (or just reduce your sleep time to 1 second)? You can use unbuffered mode with celery by running it like so:
`PYTHONUNBUFFERED=1 your_commands`

**Comment by abicorios** [comment]
Do you mean `PYTHONUNBUFFERED=1 ./manage.py runserver` or `PYTHONUNBUFFERED=1 python manage.py runserver`? It leads to an infinite waiting too.

**Comment by Chris7** [comment]
I meant through celery, not runserver. Are you running this through celery or through the main process (if you run through the main process, it will block)? Also, can you define infinite waiting?

**Comment by abicorios** [comment]
Ok. Celery. I read http://wooey.readthedocs.io/en/latest/running_wooey.html I go to myproject folder. I create Procfile with next content:
```
web:  python manage.py runserver
worker: celery -A your_project_name worker -c 1 --beat -l info
EOM
```
I run `pip install honcho`. And I run `honcho start`. So I go http://127.0.0.1:8000
Wow, I run script and it work. But it is not realtime now. I see Waiting along 1 second, and I see Executing along 10 seconds (it is default in my script, 10 iterations with 1 second waiting on each). And I see Success with full output of my script by one moment. So, it is not realtime for me.

**Comment by abicorios** [comment]
I write my autotest, how I understand it. Now it is not realtime for me. Where is my mistake?  https://github.com/abicorios/testRealtimeWooey

**Comment by Chris7** [comment]
You are still running it in buffered mode. You need to run celery like `PYTHONUNBUFFERED=1 celery -A myproject worker -c 1 --beat -l info` for more granular output, or manually flush stdout in scripts.

**Comment by abicorios** [comment]
Wow, yes! It is work! You are a guru-ninja-hacker!  Just Procfile with content:
```
web:  python manage.py runserver
worker: PYTHONUNBUFFERED=1 celery -A myproject worker -c 1 --beat -l info
EOM
```
One interesting thing: my [script](https://github.com/abicorios/slowPrint/blob/master/a.py) must print one row per second
```
time.sleep(1)
print(i)
```
But Wooey wait 3 second and print 3 row in one moment. How can I reduce 3 second waiting to 0.5 second? It is not critical for me, just like on some simple setting. Realy, Wooey is very nice for me in this state, I use it for sharing my Python scrip for several collaborators. I do not use it for thousands clients. Just several covorcers can run my script for inside useing. Now I have what I need. Wooey work with realtime out of the box.
Also, you can add an info about PYTHONUNBUFFERED=1 in the documentation, because the realtime is not work without it.
