### ISSUE TITLE
Customize look of Wooey

### ISSUE THREAD

**Issue by waltonereed** [wooey/Wooey#223]
I'm a novice in Django, so I'm not sure if this is possible, but can I customize the look of my Wooey app? For example, I'd like to add my company's logo and change the color scheme across the top banner of the site.

**Comment by Chris7** [comment]
If you are looking for something simple, `WOOEY_SITE_NAME` and `WOOEY_SITE_TAG` will let you customize a bit of the frontend. Otherwise, you would need to override the templates for additional customization and that would require a bit more knowledge of Django.

**Comment by waltonereed** [comment]
Thanks Chris, that helps a lot!
