### ISSUE TITLE
How to get the "File upload" widget?

### ISSUE THREAD

**Issue by jvshah74** [wooey/Wooey#231]
What do I need to specify in the argparse argument type for Wooey to create a widget to allow the user to upload a file? An example would help.

**Comment by jvshah74** [comment]
Currently, I'm using standard:
parser.add_argument('-f', dest='inFile', default='',...
And then manually editing the "script parameter" to:
- Uncheck "Is Output"
- Form Field = FileField
- input type = file

**Comment by Chris7** [comment]
@jvshah74 
This is how to do it in argparse:
`parser.add_argument('--file-field', type=argparse.FileType('r'))`

**Comment by jvshah74** [comment]
Thanks. That works.
