### ISSUE TITLE
how to config no buffer output on windows

### ISSUE THREAD

**Issue by etiaxie** [wooey/Wooey#238]
i setup wooey env on windows python 2.7 and my setup command like the following:
python manage.py runserver
python manage.py celery worker -c 8 -l info
after it works, when the script excute, i find the print output will not pop up on web UI until script excute finished.

**Comment by Chris7** [comment]
You need to set the `PYTHONUNBUFFERED` environment variable to avoid python buffering the output.

**Comment by etiaxie** [comment]
i don't want to change the whole python environment, just want wooey to output with no buffer.

**Comment by Chris7** [comment]
Then you are at an impasse. Wooey runs in python, so you need to control the buffering from python, or flush the `stdout` from your scripts manually.
