### ISSUE TITLE
It's possible to use calendar widget?

### ISSUE THREAD

**Issue by PheonixS** [wooey/Wooey#245]
What I need to specify to use calendar widget in argparse?
Thanks!

**Comment by Chris7** [comment]
Argparse has no notion of a calendar widget. There is a pull request that attempts to enable custom widgets on the frontend here: https://github.com/wooey/Wooey/pull/175

The way it works would be you define a field in argparse that accepts a datetime string that the calendar input uses. I never tested the custom widgets enough to feel comfortable merging it in, but would love to get some more beta testers to change that.

**Comment by Chris7** [comment]
This has been implemented in #175
