### ISSUE TITLE
wooey no longer running on windows because of dependency with celery 4.0 API

### ISSUE THREAD

**Issue by tomanizer** [wooey/Wooey#246]
wooey requires celery to run.

Celery 4 is no longer supported on windows and using it causes
` ValueError: not enough values to unpack (expected 3, got 0)`

Downgrading to Celery 3.1.25 (last version to run on windows) does not help, because Wooey uses the celery 4.0 API which uses a new 'namespace' attribute.
```
  File "wooey_celery_app.py", line 13, in <module>
   app.config_from_object('django.conf:settings', namespace='CELERY')
  TypeError: config_from_object() got an unexpected keyword argument 'namespace'.
```

Suggestion:
In celery_app.py check which version of celery is running and then use either the 3.1 or the 4.0 API.

**Comment by atyler333** [comment]
I was able to run it locally in python 3.6 on windows 10 using a modified celery command.

celery -A your_project_name worker --pooleventlet -l info

**Comment by Chris7** [comment]
That sounds great, I love PRs.

**Comment by Chris7** [comment]
Looking back, I actually did have to use `eventlet` for celery on windows as well. You can see this here:
https://github.com/wooey/Wooey/blob/master/setup.py#L22

This is also present in the docs (though the formatting seems to be broken :()
https://wooey.readthedocs.io/en/latest/running_wooey.html?highlight=eventlet

**Comment by tomanizer** [comment]
I was using pip 10.

I also have to run celery with this command.

`celery -A myapp worker -c 1 -l info -P eventlet`

**Comment by Chris7** [comment]
Closing this as the docs are up to date on this. If anyone wants to put forth a PR making the documentation more explicit and obvious in their opinion, it would be appreciated.

**Comment by tomanizer** [comment]
@Chris7 , the current docs are different from what i posted above.

the docs say you need to run

`celery -A your_project_name worker --pool=eventlet -l info`

whereas I had to run

`celery -A myapp worker -c 1 -l info -P eventlet`

is perhaps the '=' sign the culprit?

**Comment by Chris7** [comment]
It could be the concurrency argument (1). Can you try ommitting that?
