### ISSUE TITLE
How to make locale folder?

### ISSUE THREAD

**Issue by partrita** [wooey/Wooey#252]
I google [how to make locale on django](https://stackoverflow.com/questions/12946830/how-to-add-new-languages-into-django-my-language-uyghur-or-uighur-is-not-su). Then, fork the repo for fix it. But, I can not find **manage.py**  file.

Could you give me a detail, to  how to do it?

**Comment by Chris7** [comment]
Wooey is setup as a reusable app, so it is a bit different than that -- you will want to use `django-admin` and the test settings:

`django-admin makemessages --settings=wooey.test_settings --locale locale_name`.

Let me know if that helps and I would love to see another translation added to Wooey!
