### ISSUE TITLE
No output in console web view until tasks finishes

### ISSUE THREAD

**Issue by dmileta** [wooey/Wooey#253]
Running on windows, there is no console output until task is finished. Task in executing but no realtime is available

**Comment by Chris7** [comment]
This may be because python is buffering your output. See this issue and let me know if that resolves it: https://github.com/wooey/Wooey/issues/220

**Comment by Chris7** [comment]
Could you provide a copy of the script?

**Comment by Chris7** [comment]
Reopen if still a problem.
