### ISSUE TITLE
scripts stuck on waiting (Docker)

### ISSUE THREAD

**Issue by DaJansenGit** [wooey/Wooey#258]
Hey there i'm using wooey on a linux server and build it with docker by docker-compose. My scripts always stay on the waiting status and there is no output to the console. I saw the issues #48 #107 and #218 with the same problem, and tried starting the celery worker with
`python manage.py celery worker -c 1 --beat -l info`
but it seems like celery isn't even installed, because i get 
`Unknown command: 'celery'`

**Comment by Chris7** [comment]
Can you give me a step-by-step of your install/build process?

**Comment by DaJansenGit** [comment]
Thanks for the fast reply!
Here are the steps i made
1. cloned your repo 
2. run `docker-compose up`
3. added 0.0.0.0 to allowed hosts in user_settings.py
4. execed into the docker container as root and run
'python manage.py createsuperuser
 'python manage.py runserver 0.0.0.0:8000'

The server is running and i can access it, also the admin account is working. What i should mention, when i'm creating a new project with `wooify -p <projectname>` and cd into the directory and run `python manage.py createsuperuser` i get the following python error: 

> Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)

**Comment by Chris7** [comment]
I just followed these steps and everything runs:
* git clone git@github.com:wooey/Wooey.git
* cd Wooey/docker
* ./wooey-compose build wooey
* ./wooey-compose run wooey python manage.py createsuperuser
  -- fill in info
* ./wooey-compose up wooey celery
* go to `http://localhost:8081/` (or change the port in docker-compose.overide.yml), setup your script in the admin and run it.

One issue I noticed is that celery 4.1.0 is defined in requirements.txt, which is a broken release. I updated this version to 4.2.1, you may want to do the same and rebuild since celery may have crashed on startup

**Comment by dxiri** [comment]
I have this same problem, installed from pip. 

Trying to run the celery command doesn't work:
```
sjo-mpcwp:OAT_GUI dxirinac$ python manage.py celery worker -c 1 --beat -l info
Unknown command: 'celery'
Type 'manage.py help' for usage.
```
I followed the install steps on this page:
https://wooey.readthedocs.io/en/latest/install.html

How can I fix this with the pip version?

Thank you!

**Comment by Chris7** [comment]
See this: https://wooey.readthedocs.io/en/latest/running_wooey.html#through-two-separate-processes
