### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by mfitzp** [wooey/Wooey#26]
Having tested a Python3 install there are a few issues that prevent Wooey from working with Python3. We should try and sort this before the first release —

- Script runner manually passes `python` for the command. We should a) support direct script execution (`+x` and `#!` on Mac/Linux); and b) support the execution command to be set in on the `Script` model. This will be important when we start supporting other languages, non-Python scripts, etc.
- There is a `UnicodeDecode` error on returning images (and probably all files) from the celery task execution when it tests them for fastax file types. We should be able to work around all this with `six` (which is already in the requirements).

I'll add more as I squash these.

**Comment by Chris7** [comment]
@mfitzp I sort of took care of this with the bootstrap command, but forgot to include it for this. Check out this https://github.com/wooey/Wooey/pull/28 and let me know if that works -- it should as it's the same approach as the bootstrapper.

**Comment by mfitzp** [comment]
The issues found here are all working now and I've got a running Python3 test environment to catch future bugs. Closing for now.
