### ISSUE TITLE
Multi input file 

### ISSUE THREAD

**Issue by puckk** [wooey/Wooey#269]
Hi, Can I choose an unlimited number of files without use django-djangui?

**Comment by Chris7** [comment]
Hi pukk,

If the script specifies multiple arguments, like so:
https://github.com/wooey/Wooey/blob/master/wooey/tests/scripts/choices.py#L11

There will be a little `+` button next to the file input to provide additional files.

Does that solve your use case?

**Comment by puckk** [comment]
The correct way to use the script is

python --multiple-file-choices file1 file2 file3

But Wooey generates

python --multiple-file-choices file1 --multiple-file-choices 2 --multiple-file-choices file3

when I do for in the script, I only see one file

**Comment by puckk** [comment]
python T.py --multiple-file-choices file1 file2 file3 --need-at-least-one-numbers 1
Namespace(a=[<open file 'file1', mode 'r' at 0x7f38a635e780>, <open file 'file2', mode 'r' at 0x7f38a635e810>, <open file 'file3', mode 'r' at 0x7f38a635e8a0>], all_choices=None, at_least_one_choice=None, choices_str=None, more_multiple_file_choices=None, need_at_least_one_numbers=[[1]], one_choice=None, two_choices=None)



python T.py --multiple-file-choices file1 --multiple-file-choices file2  --multiple-file-choices file3 --need-at-least-one-numbers 1
Namespace(a=[<open file 'file3', mode 'r' at 0x7f0850910780>], all_choices=None, at_least_one_choice=None, choices_str=None, more_multiple_file_choices=None, need_at_least_one_numbers=[[1]], one_choice=None, two_choices=None)

**Comment by Chris7** [comment]
Well, that's most definitely a bug. I'll look at this and try to get a patch up ASAP.

**Comment by puckk** [comment]
Thanks!!

**Comment by Chris7** [comment]
Wooey 0.10.1 should fix this, can you upgrade and confirm? The script may have to be re-imported to work correctly though (or you can manually fix the `collapse_arguments` flag to `True` in the script parameters admin)

**Comment by puckk** [comment]
Confirmed. Thanks
