### ISSUE TITLE
Demo heroku, digitialocean, and openshift app installations

### ISSUE THREAD

**Issue by mfitzp** [wooey/Wooey#27]
@Chris7 Can you update the herokuapp to use the new repo at wooey.herokuapp.com? Would be good to have a demo available.

**Comment by Chris7** [comment]
@mfitzp Sure. I was going to say for documentation we can setup demo servers on some free services. I was thinking of digitialocean, heroku, and openshift for starters.

**Comment by mfitzp** [comment]
Heroku example up at: htp://wooey.herokuapp.com

Updated the title to include the other options.

**Comment by Chris7** [comment]
Fixing a bug with our ephemeral file systems with re-running jobs at the moment.

**Comment by Chris7** [comment]
Wooey at heroku is working now. Working on openshift right now.

**Comment by Chris7** [comment]
I'll update these docs shortly.
