### ISSUE TITLE
value too long for type character varying(255)

### ISSUE THREAD

**Issue by jigar-p** [wooey/Wooey#273]
I have been trying to figure out a way to have choices that is sentence long each. Since the number of characters exceed 255, I am getting the `value too long for type character varying(255)`. I checked under core.py and tried to change the script_param from CharField to TextField (`script_param = models.CharField(max_length=255))`). However, that did not work. Any suggestions how I can achieve the goal?

**Comment by Chris7** [comment]
You can do that, but you will have to create a migration to alter the database to change the field type from a varchar to a text field. I'm curious about your specific use case though, because if it's useful, Wooey itself can lift the choice limit to be a textfield and you won't have an upgrade incompatibility.

**Comment by jigar-p** [comment]
Hi Chris, 
I am working on automating documents. Instead of manually typing out bullet points that in form of sentences, you can simply select one or more from the "choices" menu. 

Example:
<img width="795" alt="screen shot 2019-03-06 at 5 59 33 pm" src="https://user-images.githubusercontent.com/24325734/53926791-a5c55f80-4039-11e9-9147-88d851ba92df.png">


If I add more objectives on the list, I get the `value too long for type character varying(255)` error. I really think it would be useful feature to have on this amazing project.

**Comment by Chris7** [comment]
I think it makes a lot of sense to change it to a TextField. I am pretty swamped atm so not sure when I can get to this, but would be willing to take a PR.

**Comment by Chris7** [comment]
Implemented via #280. Going to get a few more patches in and make an official release soon.
