### ISSUE TITLE
Subparsers with required arguments: all subparsers must validate to submit a job

### ISSUE THREAD

**Issue by slarse** [wooey/Wooey#288]
I have a fairly complicated application that has ~10 subparsers in it, many with required arguments. I don't _think_ I'm doing anything crazy, though. The problem I face is that when I try to submit a job for a specific subparser, _all_ subparsers must validate. That is to say, I need to go through all of them and enter the required arguments, then submit for the one that I want. That works, the correct arguments come through, but it's very inconvenient.

I'd wager the reason is that when I select another subparser in the dropdown, it's just made the active one, but the others are still part of the form (only hidden). Here's a small example script that ends up with the behavior I've described above.

```python
import argparse
import sys

parser = argparse.ArgumentParser(
    description="CLI app with subparsers."
)
subparsers = parser.add_subparsers(dest="subcommand")
subparsers.required = True

sub_1 = subparsers.add_parser("first")
sub_1.add_argument("--arg-one", type=str, required=True)

sub_2 = subparsers.add_parser("second")
sub_2.add_argument("--arg-two", type=str, required=True)

sub_3 = subparsers.add_parser("third")
sub_3.add_argument("--arg-three", type=str, required=True)

def main():
    args = parser.parse_args()
    print(args)
    return 0


if __name__ == "__main__":
    sys.exit(main())
```

The precise place where things go sideways is when `form.full_clean()` is called in  `wooey.backend.utils.validate_form`, which in turn is called from `wooey.views.views.WooeyScriptBase.post`, as the full form fails to validate and `form.errors` is populated. I've never used Django more than for small toy projects, so I don't know how to solve this.

https://github.com/wooey/Wooey/blob/f06285387b7f78bf2c5d84faff4f986bc0979f86/wooey/views/views.py#L84

https://github.com/wooey/Wooey/blob/f06285387b7f78bf2c5d84faff4f986bc0979f86/wooey/backend/utils.py#L182-L187

**Comment by Chris7** [comment]
You're absolutely correct. I think the best approach is to add the chosen subparser to `get_master_form` to only add fields that are in the 1) main parser 2) chosen subparser
