### ISSUE TITLE
Escaping Characters in args

### ISSUE THREAD

**Issue by danieldjordan** [wooey/Wooey#292]
Not sure where this is happening, but when I put an & in my script argument field as part of a longer string it will only pass the string up to the & to the script.  I am not sure how to escape the character I have tried " " ' ' /, but they all get passed as is.

Any thoughts on how to pass the & to the script?

**Comment by pauricthelodger** [comment]
Have you tried a backslash? `\`

**Comment by danieldjordan** [comment]
Yeah I did, sorry didn't list that. It looks like it only happens with the multiple entry fields.  If I change the arg to a standard arg it all works as expected.

**Comment by pauricthelodger** [comment]
Ah dang, sorry it was no help, could you paste an example of one that works and one that doesn't?

**Comment by danieldjordan** [comment]
You bet, give me a few and I will post some output.  Thanks for the help!

**Comment by Chris7** [comment]
Thanks for opening this. This is a bug in how the querydict was being generated on the backend, fixed in #296 . I have a few other things I want to fix before pushing a new version out, but expect one in the not-too-distant future.

**Comment by Chris7** [comment]
If you can run from master, you should be able to confirm this works
