### ISSUE TITLE
Can't add script without argument

### ISSUE THREAD

**Issue by adnan-alam** [wooey/Wooey#293]
I want to add script that don't require any type of argument to be passed by the user. But failed to add this type of script. A sample of script is given below:

```
import pandas as pd 

print("Hello World")

try:
    df = pd.DataFrame()
    li = [{"Name":  "Adnan Alam", "Age":  23}, {"Name": "Test User", "Age": 30}]
    df = df.append(li)
    df.to_csv("test_csv.csv", index=False)
except Exception as e:
    print(e)
```

I'm getting this error when try to add this script: 
```
ParserError at /admin/wooey/script/add/

No exception message supplied
```

**Comment by Chris7** [comment]
You'll need to wrap the script using argparse, as currently there is no title/description/etc. to keep track of for versions. This can be simple as:

```
import argparse
parser = argparse.ArgumentParser('My cool script')
def main():
  your_stuff_here

if __name__ == '__main__':
  main()
```
(I wrote that in github's editor, so workable code is a maybe, but that's the idea. Let me know if this helps.

**Comment by adnan-alam** [comment]
Thanks, it worked !
