### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode' with Python 3.4.3

### ISSUE THREAD

**Issue by ktkirk** [wooey/Wooey#3]
File "/gpfs/home/kirk/Web/wooey/wooey/public/views.py", line 183, in job

 [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] console = f.read().decode('utf8')

**Comment by mfitzp** [comment]
Thanks for the bug report @ktkirk. The error relates to to differences between python2.7 and python3.4 in handling encoding/decoding. I was maintaining 2.7-3.4 compatibility but hit a slightly bizarre bug with Flask on 3.4 that I couldn't figure out.

I'll look into this later today and push an update once it's fixed.

**Comment by mfitzp** [comment]
This is fixed in the latest django-based version of Wooey (available in the repo currently - PyPi release coming soon).
