### ISSUE TITLE
Installation issue pip: Cannot find README.md

### ISSUE THREAD

**Issue by nilsdebruin** [wooey/Wooey#30]
Issuing the command:

pip install wooey

Results in an error:

Running setup.py (path:/tmp/pip_build_root/wooey/setup.py) egg_info for package wooey
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/wooey/setup.py", line 3, in <module>
        with open('README.md') as readme:
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/wooey/setup.py", line 3, in <module>

    with open('README.md') as readme:

IOError: [Errno 2] No such file or directory: 'README.md'

**Comment by mfitzp** [comment]
@nilsdebruin Thanks for the bug report — the version of Wooey on PyPI is currently out of date (we are in the process of merging two projects). Can you try and install from this repository instead?

**Comment by nilsdebruin** [comment]
@mfitzp Ok! Do I need to make a git clone and then run setup.py manually?

**Comment by mfitzp** [comment]
Nope just `pip install git+http:\\...` with the repo URL should do it. Away
from the office at the moment so will double check when I'm back.

**Comment by nilsdebruin** [comment]
@mfitzp I can confirm the installation works, thanks!

**Comment by Chris7** [comment]
Thanks @nilsdebruin. Just know the repository is subject to change right now. We should be stable in a few days, but we're ironing out/find bugs between the merger of djangui + wooey as fast as we can.
