### ISSUE TITLE
XLS file import process

### ISSUE THREAD

**Issue by richardnguyen5** [wooey/Wooey#312]
Hi Wooey team, is there documentation on importing data from an XLS file into Wooey? Or an example of a Python script that reads an XLS file into Wooey?

I'm trying to adapt some Python scripts into Wooey but keep running into errors with the XLS import process.

Thanks for sharing this platform with the community!

**Comment by Chris7** [comment]
Can you let me know what you are trying to do? Maybe a link to the script you are attempting to import?

**Comment by richardnguyen5** [comment]
Hi Chris, 

My use case with Wooey is to read data from an input XLS file, run some data manipulation, and then output the results into an XLS file. 

This is the [basic test script](https://gist.github.com/richardnguyen5/e25d337772031512219fb1ec9c0cc4b6) i am running to validate that use case. It runs correctly in Wooey, but the output file is empty.  I've attached a screenshot of the result page too.

The input XLS file i used for that test is just a Excel file with a string value in cell B2.  

<img width="1350" alt="test XLS input output" src="https://user-images.githubusercontent.com/19421189/76895332-14b1d700-6890-11ea-958d-60e5ec068199.png">

**Comment by richardnguyen5** [comment]
Thanks Chris, your suggestion worked. I had to name the output file such as "output.xlsx" or default that value within my script.  Thanks! 
 
>  I think the problem is this is writing to a buffered file that never actually exists outside of the program. At the end, you could write the buffered output to a file with output_file.name
