### ISSUE TITLE
Install Script Dependencies

### ISSUE THREAD

**Issue by yapnel** [wooey/Wooey#316]
I have a standalone python script that has some package dependencies. How are the dependencies installed when the script is added to Wooey via GUI or cmdline? 

Thanks

**Comment by Chris7** [comment]
The dependencies should be present in the environment running Wooey. For my own projects, I use docker and that image has any dependencies required installed in it.

**Comment by yapnel** [comment]
I think i have misunderstood as i was thinking the end user can upload a script and it will handle the dependencies automatically by installing it. It seems like we have to install the dependencies before user can upload their script and restart the server. Is that correct? Thanks
