### ISSUE TITLE
Schedule Task Periodically

### ISSUE THREAD

**Issue by yapnel** [wooey/Wooey#318]
Hi

Is it possible to schedule a task for a specific time to run? If so, kindly show how to achieve this please?

Thanks

**Comment by Chris7** [comment]
That is currently not possible. There is a long outstanding request for api driven access to wooey. That has not been added because we need to add api tokens, which means we need a better profile page :). It's an area I'd love PRs on.

**Comment by Chris7** [comment]
Alternatively, an interface for cron-like tasks could be equivalent, so users can setup periodic jobs via the UI and those saavy enough to use cron can do it from the api.

**Comment by yapnel** [comment]
Hi Chris

I found this 'django-celery-beat' plugin that provides the scheduling capability that i'm after. I have installed it in Wooey and in the Admin panel there is a good form to define the periodic tasks. Perhaps you may want to include this into Wooey? The only downfall is the setup of the periodic task must be done in the Admin page instead of the end userpage. Wondering if the Admin panel can be incorporated into your front end?

Thanks.
