### ISSUE TITLE
Docker compose environment uses django development server

### ISSUE THREAD

**Issue by jkpr** [wooey/Wooey#326]
At our company we are thinking of running an instance of wooey to make our python scripts available to others. I noticed that it is the django development server running. So far so good, but I'm wondering how much it would take to stress out the server.

Could I recommend gunicorn?
https://docs.djangoproject.com/en/3.0/howto/deployment/wsgi/gunicorn/

**Comment by Chris7** [comment]
Sure. I wouldn't want the default to use gunicorn though, as the docker-compose is setup to really be a dev environment (but you can easily modify it to suit a more prod setup).

**Comment by jkpr** [comment]
Do you want docker-compose to be just for a dev setup? I was attracted to this project as a way to setup a quick/easy website for others to use.

Are you interested in something like this: https://docs.docker.com/compose/extends/#multiple-compose-files 
and having an override file such as `docker-compose.prod.yml` ?
