### ISSUE TITLE
Uploaded/saved files are not accessible?

### ISSUE THREAD

**Issue by hottwaj** [wooey/Wooey#33]
Files uploaded by me/created by my scripts seem to be inaccessible via the web interface?  If I click on a link to a file in the "jobs" view I get a 404 error - should something be added to `wooey/urls.py` or is this a static files path issue?

If a static files issue, are different users prevented from seeing each other's files?

Here's the 404 error:

```
Page not found (404)
Request Method:	GET
Request URL:	http://my_server:8000/wooey/jobs/9/wooey_files/my_script_14wyypr/9/test.xlsx
Using the URLconf defined in my_proj.urls, Django tried these URL patterns, in this order:
^admin/
^wooey/ ^ ^jobs/command$ [name='celery_task_command']
^wooey/ ^ ^jobs/queue/global/json$ [name='global_queue_json']
^wooey/ ^ ^jobs/queue/user/json$ [name='user_queue_json']
^wooey/ ^ ^jobs/results/user/json$ [name='user_results_json']
^wooey/ ^ ^jobs/queue/all/json [name='all_queues_json']
^wooey/ ^ ^jobs/queue/global [name='global_queue']
^wooey/ ^ ^jobs/queue/user [name='user_queue']
^wooey/ ^ ^jobs/results/user [name='user_results']
^wooey/ ^ ^jobs/(?P<job_id>[0-9\-]+)/$ [name='celery_results']
^wooey/ ^ ^jobs/(?P<job_id>[0-9\-]+)/json$ [name='celery_results_json']
^wooey/ ^ ^scripts/(?P<slug>[a-zA-Z0-9\-\_]+)/$ [name='wooey_script']
^wooey/ ^ ^scripts/(?P<slug>[a-zA-Z0-9\-\_]+)/jobs/(?P<job_id>[a-zA-Z0-9\-]+)$ [name='wooey_script_clone']
^wooey/ ^ ^scripts/(?P<slug>[a-zA-Z0-9\-\_]+)/$ [name='wooey_script_json']
^wooey/ ^ ^scripts/search/json$ [name='wooey_search_script_json']
^wooey/ ^ ^scripts/search/jsonhtml$ [name='wooey_search_script_jsonhtml']
^wooey/ ^ ^profile/$ [name='profile_home']
^wooey/ ^ ^profile/(?P<username>[a-zA-Z0-9\-]+)$ [name='profile']
^wooey/ ^ ^$ [name='wooey_home']
^wooey/ ^ ^$ [name='wooey_job_launcher']
^wooey/ ^ ^accounts/login/ [name='wooey_login']
^wooey/ ^ ^accounts/register/ [name='wooey_register']
^wooey/ ^ ^favorite/toggle$ [name='toggle_favorite']
^wooey/ ^ ^scrapbook$ [name='scrapbook']
^wooey/ ^ ^login/$ [name='login']
^wooey/ ^ ^logout/$ [name='logout']
^wooey/ ^ ^password_change/$ [name='password_change']
^wooey/ ^ ^password_change/done/$ [name='password_change_done']
^wooey/ ^ ^password_reset/$ [name='password_reset']
^wooey/ ^ ^password_reset/done/$ [name='password_reset_done']
^wooey/ ^ ^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$ [name='password_reset_confirm']
^wooey/ ^ ^reset/done/$ [name='password_reset_complete']
The current URL, wooey/jobs/9/wooey_files/my_script_14wyypr/9/test.xlsx, didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
```

Thanks!

**Comment by mfitzp** [comment]
Below is your URL and one of mine for comparison —

`http://my_server:8000/wooey/jobs/9/wooey_files/my_script_14wyypr/9/test.xlsx`
`http://localhost:8000/uploads/wooey_files/8-queens/58/solution-1.png`

It looks like the issue is the initial `wooey/jobs/9/` in your URL which may be due to the subsequent URL being relative rather than absolute. Can you find the files in the filesystem (at either of the above sort of locations)?

If you open the HTML for the result page how do the URLs look?

**Comment by Chris7** [comment]
Are you serving static files? In urls/user_urls.py you should have your MEDIA_ROOT and STATIC_ROOT being served at MEDIA_URL and STATIC_URL, respectively.

**Comment by Chris7** [comment]
Also, anyone may see an anonymous user's filers. However, logged in users may only view their own files. We are working on a shared job/file setup, but it is not implemented yet.

**Comment by hottwaj** [comment]
Sorry, I think it must be a static files settings issue (my fault) - I haven't done anything to my MEDIA/STATIC files settings...  I had started a Django installation from scratch, but without using "wooify" - which having just experimented with it it looks like that will add the STATIC etc settings that my current test project is missing.

Cheers!

**Comment by Chris7** [comment]
Ah, yes that will do it :). Glad it's all worked out now.
