### ISSUE TITLE
ipywidgets

### ISSUE THREAD

**Issue by andreacortis** [wooey/Wooey#330]
Hello, is there a simple way to include ipywidgets in the scripts?

**Comment by Chris7** [comment]
Can you elaborate more? Is this to get an interactive input or an interactive output?

**Comment by andreacortis** [comment]
What I had in mind was a way to change the parameters of the scripts interactively (during a single run of the script), so that the user could do multiple realizations of the script and perhaps observe a different graph every time, and/or record the output of each set of inputs. I am not sure if this is feasible in wooey.

**Comment by Chris7** [comment]
This isn't really possible since Wooey runs a job and then saves its output. There isn't any active kernel running (like jupyter has). To compare parameters, users can use the `clone` button, which will generate a new job with the previous parameters if they with to tune it.
