### ISSUE TITLE
how to change the theme of wooey project?

### ISSUE THREAD

**Issue by Fatalerr** [wooey/Wooey#331]
Hi,
I create a new project with `wooify -p myproject` and want to change the theme of it. but I found it didn't take effect after I changed or modified the css file under  `myproject/myproject/static/wooey/css/base.css`.   Any comment or hint is welcome.

**Comment by Fatalerr** [comment]
After some investigation, I found the templates and static files used by `myproject`  are located at the  `wooey` directory under the system python site-packages instead of under the `myproject`.  so, Is there any way to change the `static` directory to `myproject`?

**Comment by Chris7** [comment]
Hi @Fatalerr ,

There are a few way to extend application templates, one way I've used in the past is

```
{% extends "wooey:wooey/base.html" %}
...
overwrite blocks in wooey's base.html
...
```

There's a bit on stackoverflow about this: https://stackoverflow.com/questions/3967801/django-overriding-and-extending-an-app-template
