### ISSUE TITLE
scrapbook function not works

### ISSUE THREAD

**Issue by congmaowang** [wooey/Wooey#335]
Scrapbook function not works, even in the demo https://wooey.herokuapp.com/

**Comment by Chris7** [comment]
Thanks for the report, I have a suspicion that this is related to the job cleanup code.

**Comment by Chris7** [comment]
I found the issue and have a MR to resolve this. Thanks for the report!

**Comment by congmaowang** [comment]
Thanks for fixing it, it works! Better to also update the demo https://wooey.herokuapp.com/
