### ISSUE TITLE
tar.gz is tar archive but not gzip compressed in 'All Files'

### ISSUE THREAD

**Issue by congmaowang** [wooey/Wooey#341]
Can check demo https://wooey.herokuapp.com/jobs/19430/ for example.
Cat_Fetcher_20210814-1626.tar.gz is tar archive but not gzip compressed.

**Comment by Chris7** [comment]
In what way is it not gzip compressed?
```
➜ gunzip -l Cat_Fetcher_20211219-2059.tar.gz 
         compressed        uncompressed  ratio uncompressed_name
             166412              184320   9.7% Cat_Fetcher_20211219-2059.tar
```

**Comment by congmaowang** [comment]
Use Google Chrome browser under Linux/Windows/Mac to download can reproduce this bug.
It seems works for Firefox or via command line curl to download the tar.gz file.

**Comment by Chris7** [comment]
This is a chrome issue: https://stackoverflow.com/questions/68112512/disable-chromes-gzip-automatic-decompression
