### ISSUE TITLE
icon or logo when add script

### ISSUE THREAD

**Issue by congmaowang** [wooey/Wooey#343]
Is it possible to add the icon or logo option for 'manage.py addscript', which can add the logo for each script.

**Comment by Chris7** [comment]
Do you mean the markdown for the description/documentation??

**Comment by congmaowang** [comment]
No. The icon or logo for each script.
For example in your demo https://wooey.herokuapp.com/, is it possible to add the icon or logo for the "Cat Fetcher" ?
