### ISSUE TITLE
path selector

### ISSUE THREAD

**Issue by lfaino** [wooey/Wooey#347]
Dear Developer

I have a question. Starting that i love your work, I would like to know if it possible to add a path selector in wooey? I`m working with users that do not have access to the server PC and therefore are not able to navigate the remote PC. do you think that it could be possible to add a path browser/selector in wooey to specific args parser options?

Cheers
Luigi

**Comment by Chris7** [comment]
Hi @lfaino,

This would not be possible as anything specific to argparse. If you'd want to do it, you would have to make a custom widget with your own javascript that would make the remote PC directory browsable. Wooey supports custom widgets (https://wooey.readthedocs.io/en/latest/customizations.html#form-widgets), but there is no support here for custom javascript. You could do that by loading your own javascript in a wooey template.
