### ISSUE TITLE
Private UUID URLs

### ISSUE THREAD

**Issue by mfitzp** [wooey/Wooey#36]
Current job URLs are in the format `/job/<id>` with an authorisation check on access. This prevents users from sharing the output of jobs with non-users (the in-app sharing will solve for members but not otherwise, e.g. think "sharing outputs in a paper"). Similarly there is no support for private anonymous jobs - even if the global job queue is turned off any job can be found by incrementing the ID.

There is an example available here (on a NMR service called Bayesil): http://bayesil.ca/nmr_requests/7e0d236e5860da6514a4207d0590efc9e15015cb/status

Adding support for slug-a-like md5 hash would allow us to -

- support URL sharing for completed/running jobs (email the URL to a collaborator)
- let anonymous users can have private jobs (if links are disabled in the global queue) - they will need to remember/bookmark the job page (or we can support an email field for notifications, etc.)
- store files under the same hash-url to make it possible to serve outputs (files, images, etc.) without authentication taking the load of the Django server

Implementation wise an auto-filling slug field would probably do it?

**Comment by Chris7** [comment]
At a basic level, we don't have control of the static asset serving from Django so this feature is essentially a requirement for any illusion of privacy for your file outputs.

I agree with your points, but think a hash would be ugly as a basic access url for the user, so I like the job id approach at the moment since it just looks cleaner on the url line. I would like to keep that if we can instead of having a url polluted with an indecipherable hash.

What do you think about this (it's basically your list minus point 1):
1) Keep the url structure for the general job.
2) A hash is automatically generated on submission, where files are stored. We're already setup to do this easily since each job has a separate method -- save_path we can just change.
3) The job may also be accessed by the aforementioned hash to allow sharing with anyone.

What do you mean private jobs for anonymous users? One issue I see is that if someone creates an anonymous job, anyone can just take it offline since there are no authentication procedures in place. Do you mean not having a url like /job/id and just /job/hash?

**Comment by mfitzp** [comment]
Yep agreed - it is also a bit more secure to make the non-shareable URLs the default within the UI.

The idea would be that jobs can be accessed via `/job/<id>/` which would perform the permissions/authentication while `/job/<hash>/` would not. As you say files for jobs would always be stored under `/wooey_files/<hash>/` to keep them 'safe'.

The `/job/<hash>/` URL can be shared (e.g. via the inbuilt Share button) via email/etc. to give anyone access to the job - but without permissions to do anything to the job ("view mode").

For the private-anonymous jobs the `/job/<id/` URL would always fail and following submission the user would be redirected to `/job/<hash>/` with an appropriate warning to bookmark the following page. I imagine configuring this via some setting e.g. `WOOEY_PRIVATE_ANONYMOUS_JOBS`

In this 'mode' the global queue would also not contain links to the jobs - so effectively the job is private except for the person receiving the hash URL on load.

**Comment by Chris7** [comment]
Hmm, so how would a user handle longer running jobs? And be notified when they are done? This sounds like primary territory for using Django sessions. We can have a list of jobs active for a given session so they can receive updates on their progress.

**Comment by mfitzp** [comment]
The issue then is if the session expires (overnight, lunch) the job is gone for good - unless I'm mis-remembering how they work?

I'm thinking along the lines of the site linked above where labs will have public scripts they want to make available for people to use but without the login requirement or the sharing of outputs. I can imagine people being a bit cagey about uploading their data if it (and the results) become public.

The notification could be handled by adding an email field for non-logged-in users but I guess that's a different issue?

**Comment by Chris7** [comment]
I meant we could do both. Currently if the user leaves and doesn't bookmark it -- it's gone forever as well.  We can put a message on top of the job mentioning this. I just meant it as a mechanism where the user could have some idea of job progress-etc. if the session is still active.

**Comment by Chris7** [comment]
We can store it like session.job_list for the anonymous user and update that list with additional jobs. The job queue status/completed/etc. could be sent that list with their respective status to update. This would be basically an extension of what we currently do, we just update the list of jobs to check/return with the provided hashes.

**Comment by Chris7** [comment]
We can work out those details later. We're on the same page for the implementation, this is just an enhancement so we can treat it as such.

**Comment by mfitzp** [comment]
> Currently if the user leaves and doesn't bookmark it -- it's gone forever as well.

So when an `AnonymousUser` session expires the job is currently deleted? How is that handled? I would have thought with `User=None` on the model it would persist forever.

I'll take a look at implementing the md5 slug for sharing now and we can leave the anonymous stuff to later. It's a broken bit of the UI at the moment (there is a share button but the shared link is useless).

**Comment by Chris7** [comment]
I meant if the user didn't remember/copy down/etc. the url provided. It isn't deleted from the database, it's just a job nobody knows about.

**Comment by mfitzp** [comment]
Ha :) OK I thought I was going mad. The difference is that the `/job/<id>/` URLs are guessable. So we couldn't have private anonymous jobs (nobody else can see the outputs/data) without also having unguessable URLs for anonymous users. Otherwise you could just run a script against the server trying ids in turn and download all the Nature paper goodness.

I think this is now 2 issues - the md5 sharing url (and private static files) and the private anonymous users. I'll work on the former and once complete create a new issue for the anonymous user stuff.

**Comment by Chris7** [comment]
:+1:

**Comment by mfitzp** [comment]
Implemented in #69
