### ISSUE TITLE
Additional site config options

### ISSUE THREAD

**Issue by hottwaj** [wooey/Wooey#37]
Hi guys, there are a couple of things that I've wanted to configure for an internal Wooey site:
1. prevent registration whilst still using Django Auth
2. apply different branding (e.g. replace "Wooey!" and "A web ui for python scripts")

I've made corresponding changes to a fork I have which I can add as a PR(s) if you want, or you may want to work out a preferred way of doing these things yourselves (if at all).  Let me know either way.

Cheers

**Comment by mfitzp** [comment]
Thanks @hottwaj yep let's see the PR. Both those things are things that should be available.

The ability to change the name from the settings was supposed to be in the new interface I just forgot! :)

**Comment by Chris7** [comment]
@hottwaj. You can prevent registration by setting WOOEY_AUTH to False and setting WOOEY_LOGIN_URL and WOOEY_REGISTRATION_URL to where they belong. This should allow you to use whatever backend you have setup (though I admit it's pretty untested).

**Comment by hottwaj** [comment]
@Chris7 I'm probably just missing some config detail for the registration/auth stuff, so I'll leave that for now.  For my site my aim was to use Wooey's login bar but to prevent registration, and I couldn't find a combination of existing settings that would allow that - but maybe I'm missing something.

I've added a PR for the site branding stuff, though some additional work is needed.  I'm happy to finish the missing items off - just let me know if the initial steps taken are acceptable (or otherwise!)

Cheers

**Comment by Chris7** [comment]
@hottwaj. Sounds good. So you have a login system without any user registration? You could just point the registration url to your wooey base page, which would leave the text there but prevent registration.

**Comment by mfitzp** [comment]
> my aim was to use Wooey's login bar but to prevent registration

@hottwaj Do you mean to keep the bar at the top of the page but hide the login/registration parts? So you can keep the queues visible etc.

**Comment by hottwaj** [comment]
@Martin, I was hoping for users to be able to use the login box but hide
the registration link (users are granted access internally).  From memory I
think if I set WOOEY_AUTH to false I can't use the login box, but I wanted
to keep that working.

Possibly just a set of circumstances only relevant to our setup that won't
come up for others, so no need to worry if this seems unusual.  It was easy
for me to patch our local copy to remove the registration feature .

Cheers

**Comment by Chris7** [comment]
@hottwaj. You're right, django templates don't let us easily remove that. It's one of the most annoying aspects of Django's template system imo (the infinite recursion you end up with overriding app templates). Currently the solution is what you did, copy/paste our template and remove the tag.

**Comment by mfitzp** [comment]
We should probably still add a config for this as hiding the link/form in the template doesn't prevent registration by someone manually submitting a form - this could be a security issue if registered users are given permissions to do something others aren't.

@Chris7 might be worth considering using `django-registration` to handle user registration (it has a `REGISTRATION_OPEN` configuration). The [django-registration-redux](https://github.com/macropin/django-registration) is actively maintained and supports a lot of use-cases out of the box.

**Comment by Chris7** [comment]
I don't think there's a security issue. If registrations are open, they're open. That's a site level issue instead of a template one.

I think the way to do it is to remove the registration url, which would close registration. We currently have this by the WOOEY_REGISTER_URL setting. We can add a check for None that would remove the link and indicate not to add that to the url routing.

**Comment by mfitzp** [comment]
Ah cool. I didn't see that the `WOOEY_REGISTER_URL` was going into the `urls.py` to define the route — was thinking the form view would still be active just "invisible".

We can test for an empty `WOOEY_REGISTER_URL` in the template (it'll need to be `""` to work with the `urls.py`) and then just hide the link. This was a bit fiddly to support both `as` assignment and display on the `get_wooey_setting` tag but it's a PR here #57

**Comment by mfitzp** [comment]
@hottwaj if you set `WOOEY_REGISTER_URL=""` in your settings you should now see the registration url disappear.
