### ISSUE TITLE
API Keys management interface

### ISSUE THREAD

**Issue by andchir** [wooey/Wooey#386]
https://wooey.readthedocs.io/en/latest/api_keys.html
Hello. Here I see a screenshot, but I do not see this functionality in the admin panel. How can I enable it? I have added the line
`WOOEY_ENABLE_API_KEYS = True`
to **user_settings.py**
But the api key management interface did not appear. Please, help.
[](https://wooey.readthedocs.io/en/latest/_images/api_key_view.png)

**Comment by Chris7** [comment]
Hi, are you installing from git master or pypi?

**Comment by andchir** [comment]
Hi @Chris7 From pypi.

**Comment by Chris7** [comment]
I think you can install the latest via the `v0.13.2rc1` release candidate

**Comment by andchir** [comment]
@Chris7 Yes, I installed from the repository. It works now. Thank you very much!
