### ISSUE TITLE
celery not using user setting

### ISSUE THREAD

**Issue by lfaino** [wooey/Wooey#396]
Dear Developper

I'm having some problems with Celery. I tried to set variable like amqp user and password but this is not working.
Calery is not picking up the new settings.

can you help, please

best reagds
L

**Comment by ljluestc** [comment]
Could you please give more debugging outputs? Look for any runtime errors or exceptions in the Celery logs that may indicate problems with loading or applying the configuration settings. These errors can provide valuable clues about what might be going wrong.

**Comment by lfaino** [comment]
I did find the problem. I had to specify like this

CELERY_BROKER_URL =
