### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Chris7** [wooey/Wooey#40]
We should come to an agreement on code style to help contributors. I think a tool like flake8 works nicely so we can ignore code styling elements we don't care about (such as E501 for line length).

@mfitzp You can try it with: flake8 wooey --ignore=E501 --exclude tests/*,*.pyc,wooey/tests/media/*

**Comment by mfitzp** [comment]
Definitely and :+1: for PEP8 to keep things simple. I'm using PyCharm which auto-highlights non-PEP8 code so I've been picking it off bit by bit, but that's not good for clarity in commits.

Flake8 looks great haven't used that before think that's a good standard to work on — I think there is a way to get that into a pre-commit hook.

I've previously used a tool called pep8ify that automatically fixes PEP8 errors. It's not foolproof (it occasionally dies on a file and leaves it unchanged) but it caught most of the errors reported by flake. I've opened a PR with the result so you can see it.

**Comment by Chris7** [comment]
We could put a prehook in as well as add it to our test suite Makefile
