### ISSUE TITLE
Script Versioning URLs

### ISSUE THREAD

**Issue by mfitzp** [wooey/Wooey#43]
Updating scripts changes the URL for the script with the slug being appended a number (it currently goes `-2-2-2-2-2-2-2` which is ugly).

Modified scripts should keep the same URL. Viewing a script by the slug should show the latest version by default but other versions should be available via permalinks, e.g. `/my-awesome-script/version/3`

This should be manageable by setting `slug` to be unique together with the version.

Currently uploading a new script overwrites the previous one anyway, so the versions are not different.

**Comment by Chris7** [comment]
The old version is not overwritten currently. At least it should not be, since django automatically resolves file name conflicts with the new upload.

I agree 100% with the version change. That's a great idea.

**Comment by Chris7** [comment]
This will be a backwards-incompatible change with users with existing upgraded scripts since the format of /slug/version/# will be changed. It's not a problem since this is a live branch, but just something to keep in mind.

**Comment by mfitzp** [comment]
How is the url change backwards-incompatible? The old non-versioned format shouldn't clash (no `/` in the matching path)

**Comment by Chris7** [comment]
It's incompatible only with a subset of scripts, those which are upgraded already will have missing version numbers and will not have the format of slug/version/#, but slug-2-2-2-2/version/17 or whatever. I realized I can fix this in the migration though, so I'll edit that.

**Comment by mfitzp** [comment]
Closed by #45 :+1:
