### ISSUE TITLE
Remote bulk-import of scripts

### ISSUE THREAD

**Issue by mfitzp** [wooey/Wooey#46]
Add support for bulk-importing multiple scripts (optionally from a remote URL). The use-case I'm thinking would be to have repositories ("BioWoo" etc.) containing bundles of useful-for-everyone scripts that new installations can import, e.g.

    python manage.py add_scripts https://github.com/wooey/biowoo/archive/master.zip

We could simplify this further by adding an in-built set of bundle names somehow, e.g.

    python manage.py add_scripts biowoo

...and all the scripts would be installed and set up automatically. A nice way to get from a fresh installation to a completely working/useable system. We could also add support for this in the admin panel (I'd suggest installating bulk-sets like this under a specific script group so they can be bulk activated/deactivated/deleted).

**Comment by Chris7** [comment]
Can go in with the ideas from #15 as well.

**Comment by mfitzp** [comment]
Ah good point missed that. For an example of a good library of scripts there is https://github.com/jorvis/biocode this library available which contains a large number of Python scripts predominantly for working with FASTA currently. The scripts are well-designed and documented (with a  file-header text block something we might want to support in preference to a separate markdown file?) One issue is that they use strings for the input/output file so the `FileField` will not get picked up.

Think it might be worth forking it (into the Wooey org) and applying the neccessary changes to get it to work and see if they'll accept a PR?

**Comment by Chris7** [comment]
That is bizarre they don't use the filetypes. The only case I've done something similar was when I had an argument that could be a file or a directory (do you ever do this?). If they're interested and it'd be helpful, why not. It would give users the ability to preload wooey with a ton of biological scripts.

**Comment by mfitzp** [comment]
See #55 for a first implementation.

Regarding biocode it may simply be that they don't know about it — I first discovered they were there when I was working on Wooey :) They have pretty strict design guidelines/etc. so I suspect they'll be keen on doing it "the right way". I'll fork it into the wooey org and convert them (probably be able to do most of it automatically).

**Comment by mfitzp** [comment]
Closing this in favour of #15
