### ISSUE TITLE
Submitted jobs stuck on 'waiting'

### ISSUE THREAD

**Issue by CatherineH** [wooey/Wooey#47]
I've submitted a job, it appears to be stuck on waiting. 
It exists in the jobs and in the queue. 
There are no error messages in the screen where python manage.py runserver is running.
The script is executable.

Is there a way that I can get wooey to spit out what it tried to do with celery?

**Comment by mfitzp** [comment]
Excuse the daft question but have you started the celery task runner? e.g.

    python manage.py celery worker -c 1 --beat -l info

This needs to be started in a separate process (e.g. terminal window if you're doing a local development server). You should be able to see any script error output in that window also.

Let me know if you have done that and it's still not working.

**Comment by CatherineH** [comment]
oh derp, yep, that is it. I misunderstood the readme.

**Comment by Chris7** [comment]
You can simplify it using honcho as well -- there is an example in the docs of this.

**Comment by mfitzp** [comment]
:+1: I'll update the documentation to put the more-recommended methods up front.

**Comment by mfitzp** [comment]
Updated README here: https://github.com/wooey/Wooey/blob/rtd/README.md

**Comment by CatherineH** [comment]
The new documentation is better. Thanks!
