### ISSUE TITLE
md5 hashing of uploaded files

### ISSUE THREAD

**Issue by Chris7** [wooey/Wooey#48]
Hashing of files so they can be used by all scripts and lower storage requirements. For instance, fasta files are very redundant to have uploaded per job.

**Comment by mfitzp** [comment]
Would this be some kind of local storage? It would be nice to make uploaded files + outputs of other files available to use in subsequent jobs through a custom file widget.

**Comment by Chris7** [comment]
I agree. It was referenced in #21, and I did some work on djangui that rendered all users files uploaded/output as a jstree in the file upload. You can check i tout here:

https://www.jstree.com/

I still have that branch and will check out how it integrates with wooey.

**Comment by Chris7** [comment]
Preview of how that currently works after rebasing onto wooey:

![wooey _jstree1](https://cloud.githubusercontent.com/assets/963909/9470993/62b7d45e-4b1c-11e5-906f-66db2066106e.png)
![wooey _jstree2](https://cloud.githubusercontent.com/assets/963909/9470994/62bccaea-4b1c-11e5-9e78-5461420a6897.png)

**Comment by Chris7** [comment]
You can check it out on the wooey/jsTree branch. It's a tad rough but I was considering going down the route of a more universal media management widget.

**Comment by Chris7** [comment]
A note why I left the tree idea where it was:

I realized what we need is a way for users to share files and have file access. Basically, what I think we actually need is a generic file view that offers the functionality of:
1) Share a file.
2) Delete a file.
3) ...

With a generic widget, we could replace the one that lists all the files in the job view, give a global overview of the files a user has access to on the script input, and have an overview of all the files/sharing/etc. in their dashboard. I think jsTree may be able to do these things for us, but I left it to check out if any django based solutions for media management existed (that may have extra bells and whistles like file previews/etc.).

**Comment by Chris7** [comment]
We should use a sha-1 sum instead of md5 here.

**Comment by Chris7** [comment]
Initial work is underway #98

**Comment by Chris7** [comment]
Implemented via #98
