### ISSUE TITLE
Cloning jobs: corrupted parameter input values

### ISSUE THREAD

**Issue by hottwaj** [wooey/Wooey#50]
Hi guys, when I clone a job some of my parameter values get corrupted in the view of the cloned job that is presented to the user.  

For example, say I originally entered the value "test string" into the text box for one of my parameters.  If I run the job and then clone it, then the view of the cloned job now shows a text box with the inital value for my parameter as:
[u'test string'] 

This seems to occur to all of the optional args that have string values.  

It also happens to "output file" type args, except that if I originally entered something like "test.txt" as my output filename, then on the cloned job screen the filename appears in a text box as:
`[<File: /full path to my wooey install/user_uploads/wooey_files/admin/jspricpt id/job id/test.txt>]`

I had a quick look through the source but couldn't determine if the best place to fix this is in ScriptParameters.value() in core.py, or in WooeyScriptBase.get_context_data() in views.py?

Note that this issue does not occur for array input parameters (e.g. with choice limit >=1).  These are correctly output without the extra [u''].

Thanks

**Comment by Chris7** [comment]
Hey @hottwaj. Can you let me know if this is against the latest wooey? I just tested with a multiple choice field and it worked as advertised. Otherwise, could you provide a gist of your script so I can see what particular aspect is causing Wooey to fail?

**Comment by hottwaj** [comment]
Hi @Chris7, I'm using a version from around mid-August.  I'll try again with the latest as soon as I get some time to update.  It will also take me a bit of time to doctor my script to a form that I can send to you, so I'll have to sit on that for now too.

In the meantime could you try again with a raw text input field, rather than multiple choice?  Just to be clear, here are some screenshots of the kind of initial values I'm seeing when I clone a job:

![image](https://cloud.githubusercontent.com/assets/5629061/9474684/05abee24-4b5a-11e5-9264-349c8611c8c4.png)

![image](https://cloud.githubusercontent.com/assets/5629061/9474703/1f1a8a46-4b5a-11e5-8fa6-b9f7db481b9f.png)

**Comment by Chris7** [comment]
I'm sorry, that was misleading. I meant multiple choice as a field that accepts multiple values, such as:

parser.add_argument('--choices-str', nargs='+', type=str)

Alternatively, can you just just me the add_argument bit that is failing?

**Comment by Chris7** [comment]
This is how it appears natively:

![image](https://cloud.githubusercontent.com/assets/963909/9474958/a8fcf812-4b31-11e5-991e-9ab93947cccb.png)

On filling out/cloning:
![image](https://cloud.githubusercontent.com/assets/963909/9474964/b1f55324-4b31-11e5-9d2a-c8dae841221a.png)

**Comment by Chris7** [comment]
Another question: are you using a caching backend? I have encountered this situation before where the cache was storing lists as strings, and they came back in a similar fashion.

**Comment by hottwaj** [comment]
Hi @Chris7, the args that are causing issues when cloned look like this:

parser = argparse.ArgumentParser()
parser.add_argument("--output_filename", type=argparse.FileType('w'), required=True, help="Name of Excel output file.")
parser.add_argument("--due_date_field", type=str, help="Column name for due date field. 'Due Date' by default.")

I'm still using a django installation as set up using "wooify", which I don't think has any caching by default?

Thanks

**Comment by Chris7** [comment]
Thanks @hottwaj. I can recreate that issue locally now and will fix it.

**Comment by hottwaj** [comment]
Great!  Thanks a lot for looking at this

**Comment by Chris7** [comment]
Fixed in #53

**Comment by mfitzp** [comment]
@hottwaj the fix from #53 (a861922) has now been merged. Can you check and see if it is working for you?

**Comment by hottwaj** [comment]
That's great @Chris7, and sure thing - I'll try and check it out today or tomorrow when I have a moment

**Comment by hottwaj** [comment]
@Chris7 your fix in the version I pulled yesterday works perfectly - thanks!
