### ISSUE TITLE
Bring user to error fields

### ISSUE THREAD

**Issue by Chris7** [wooey/Wooey#51]
With the tabbed setup, sometimes users cannot see an error. The UI should navigate to the errors automatically.

**Comment by mfitzp** [comment]
I've implemented this in the attached PR. Basically when there is a form error it looks for a parent tab and sets an error state on it. If it's the first tab found with an error it will also change to that tab.

That PR will also have fixes for the scrapbook number not updating (always shows 0) and a couple of other annoyances.

**Comment by mfitzp** [comment]
Closed by 53a5157
