### ISSUE TITLE
.xlsx files are sometimes detected to be FASTA files

### ISSUE THREAD

**Issue by hottwaj** [wooey/Wooey#61]
This causes the binary contents of a .xlsx file to be displayed in the Job view.  

I just tried testing a basic .xlsx file though and this problem didn't occur, so it doesn't always happen...  If I come across a basic file that contains data I'm allowed to upload as an example I will do so.  Thanks

**Comment by hottwaj** [comment]
For now, see screenshots below

![image](https://cloud.githubusercontent.com/assets/5629061/9662483/824a87b6-5257-11e5-9e44-9ca68314ff58.png)

![image](https://cloud.githubusercontent.com/assets/5629061/9662516/a70a5842-5257-11e5-88af-466567a51aac.png)

**Comment by Chris7** [comment]
Ah, I see why this is happening. It's because you have somewhere in this binary stream a row beginning with a >. It's a problem of the fasta file parser not enforcing the start character being >. Thanks for the report.

**Comment by Chris7** [comment]
Fixed in #64
