### ISSUE TITLE
ScriptParameter short_param should be allowed to be blank

### ISSUE THREAD

**Issue by hottwaj** [wooey/Wooey#62]
Same may apply to script_param

Otherwise admin site comes up with an error if you try to change other fields of a ScriptParameter instance:

![image](https://cloud.githubusercontent.com/assets/5629061/9681004/cabe4988-52f2-11e5-9913-ae87963f24b0.png)

**Comment by hottwaj** [comment]
p.s. the arg causing a problem here was defined this way:
`parser.add_argument("input_files", type=argparse.FileType('r'), nargs='+', help="...")`

**Comment by Chris7** [comment]
Fixed in #63. Thanks as usual for your help.

**Comment by hottwaj** [comment]
No problem - thanks for the quick fixes!
