### ISSUE TITLE
Issue running manage.py db init 

### ISSUE THREAD

**Issue by streetmapp** [wooey/Wooey#7]
I'm trying to follow the steps you have listed, and in running the first manage.py command, I encountered an issue. Not sure what I'm missing here of there's something else in play.

I am using Python 3.4.3 for this.
```
manage.py db init
Traceback (most recent call last):
  File "/Users/streetmapp/dev/scripts/Wooey/manage.py", line 18, in <module>
    from wooey.app import create_app
  File "/Users/streetmapp/dev/scripts/Wooey/wooey/app.py", line 16, in <module>
    from wooey import public, user, admin
  File "/Users/streetmapp/dev/scripts/Wooey/wooey/admin/__init__.py", line 4, in <module>
    from . import views
  File "/Users/streetmapp/dev/scripts/Wooey/wooey/admin/views.py", line 14, in <module>
    class ModelView(ModelView, AdminView):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by mfitzp** [comment]
Thanks for trying out Wooey and reporting the bug.

This is probably a Python 3 issue as Wooey is currently only Python 2.7.
Making it compatible is a major priority at the moment, unfortunately there
is something in the script parsing (AST) that is broken on Python 3 which I
have to fix before I can get to the rest of it. I am working on it though!

**Comment by streetmapp** [comment]
No worries. 

I was looking for some insight about what version of Python needed to be used for Wooey to run, but couldn't find it. And that (running with Python 2.7) was going to be my next step.  

Do the scripts used also have to be Python 2.7? Or can those be Python 3 as it's more important for Wooey to be on Python 2.7?

**Comment by mfitzp** [comment]
The scripts themselves can be Python3 as long as the source parses as valid Python2.7. That’s where the issue currently is (the parser used to find the `argparse` object is Python2.7 only).

On 10 May 2015 at 00:06:42, streetmapp (notifications@github.com) wrote:

No worries.

I was looking for some insight about what version of Python needed to be used for Wooey to run, but couldn't find it. And that (running with Python 2.7) was going to be my next step.

Do the scripts used also have to be Python 2.7? Or can those be Python 3 as it's more important for Wooey to be on Python 2.7?

**Comment by streetmapp** [comment]
I got a little farther with 2.7, but still an issue when running the initial steps.

```
/Users/streetmapp/dev/env/wooey/bin/python /Users/streetmapp/dev/scripts/Wooey/manage.py build_scripts
INFO:root:Processing file ./scripts/8 Queens Problem.py.
Traceback (most recent call last):
  File "/Users/streetmapp/dev/scripts/Wooey/manage.py", line 302, in <module>
    manager.run()
  File "/Users/streetmapp/dev/env/wooey/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/streetmapp/dev/env/wooey/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/streetmapp/dev/env/wooey/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/Users/streetmapp/dev/scripts/Wooey/manage.py", line 78, in build_scripts
    collect_argparses(scripts)
  File "/Users/streetmapp/dev/scripts/Wooey/wooey/backend/python.py", line 54, in collect_argparses
    if parsers:
UnboundLocalError: local variable 'parsers' referenced before assignment
```

**Comment by mfitzp** [comment]
Now *that* was a bug. I’d messed up some indentation in an applied patch. The fix is pushed up to github, are you able to install from the repo or do you need a `pip` release?


On 10 May 2015 at 00:48:52, streetmapp (notifications@github.com) wrote:

I got a little farther with 2.7, but still an issue when running the initial steps.

/Users/streetmapp/dev/env/wooey/bin/python /Users/streetmapp/dev/scripts/Wooey/manage.py build_scripts
INFO:root:Processing file ./scripts/8 Queens Problem.py.
Traceback (most recent call last):
  File "/Users/streetmapp/dev/scripts/Wooey/manage.py", line 302, in <module>
    manager.run()
  File "/Users/streetmapp/dev/env/wooey/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/streetmapp/dev/env/wooey/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/streetmapp/dev/env/wooey/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/Users/streetmapp/dev/scripts/Wooey/manage.py", line 78, in build_scripts
    collect_argparses(scripts)
  File "/Users/streetmapp/dev/scripts/Wooey/wooey/backend/python.py", line 54, in collect_argparses
    if parsers:
UnboundLocalError: local variable 'parsers' referenced before assignment

**Comment by streetmapp** [comment]
That did it, thanks. Now off to get working on moving my click script over to argparse. Thanks for the assist.

**Comment by streetmapp** [comment]
I can certainly move my inquiries to a new area if using this isn't proper, but I'm seeing odd behavior with trying to generate new scripts/copies of the sample scripts. I can't get anything to run unless I use the sample scripts or copy the actual sample file to a new named file. 

For instance, I can copy IMDB.py to say testing.py, run build_scripts and find_scripts and I can call testing just like IMDB.  But if I copy the contents of a script into a new blank file, run the same steps, it errors out. 

And this is what is output on the start_daemon process when it fails:

```
INFO:root:Starting job 8.
ERROR:root:
```

**Comment by mfitzp** [comment]
That’s very strange, and a similar no-errors bug has been reported elsewhere.

Did you mark the new script as executable?  (chmod +x my_new_script.py)

On 10 May 2015 at 02:20:25, streetmapp (notifications@github.com) wrote:

I can certainly move my inquiries to a new area if using this isn't proper, but I'm seeing odd behavior with trying to generate new scripts/copies of the sample scripts. I can't get anything to run unless I use the sample scripts or copy the actual sample file to a new named file.

For instance, I can copy IMDB.py to say testing.py, run build_scripts and find_scripts and I can call testing just like IMDB. But if I copy the contents of a script into a new blank file, run the same steps, it errors out.

And this is what is output on the start_daemon process when it fails:

INFO:root:Starting job 8.
ERROR:root:

**Comment by streetmapp** [comment]
Well I feel silly now, as that took care of that issue. I'm now able to get other scripts functional that aren't direct copies of the example scripts.

Another functionality question, does this presently support subparsers? Leveraging a simple example that does work on the command line, it has an issue when I run ```python manage.py build_scripts```.

**Comment by mfitzp** [comment]
No problem, there really should be a more informative error. I'll look at
how yo do that.

There is no subparser support at the moment but I plan to add it soon.

**Comment by mfitzp** [comment]
Python3 is now supported (in the merged wooey+djangui project). Subparser support is now here: https://github.com/wooey/clinto/issues/2
