### ISSUE TITLE
WOOEY_SHOW_LOCKED_SCRIPTS = False

### ISSUE THREAD

**Issue by hottwaj** [wooey/Wooey#82]
Hey guys, this setting does not prevent disabled scripts from being displayed (contrary to the docs).

**Comment by Chris7** [comment]
ha, I just made a branch for this too

**Comment by mfitzp** [comment]
Ha :) ...should probably have assigned it before it. I also realised that I hadn't pushed the version bump either so that came in with it (but on separate commits).

@hottwaj this should work now!

**Comment by hottwaj** [comment]
Thanks guys!
