### ISSUE TITLE
True/False params are not output when executing a command

### ISSUE THREAD

**Issue by hottwaj** [wooey/Wooey#86]
Hey guys, I have an argument that looks like this:
```
main_options_group.add_argument('--my_optional_arg', default=False, action='store_true')
```

This is correctly stored as a ScriptParameters object when I tick the checkbox in the Wooey interface.  However when Celery executes the command it does not include --my_optional_arg in the command that is executed.

Looking at the source, it seems that `param.get_subprocess_value()` does not return a "value" for the param, causing the condition in the "if" statement on line 79 of utils.py to fail and ultimately preventing the param from being output correctly. 

See my pdb log below.  You can see that after executing line 78 "subproc_value" is None, despite param.value being True

```
(Pdb) l
 73  	        if subproc_dict is None:
 74  	            continue
 75  	        subproc_param = subproc_dict['parameter']
 76  	        if subproc_param not in param_dict:
 77  	            param_dict[subproc_param] = []
 78  ->	        subproc_value = subproc_dict.get('value', None)
 79  	        if subproc_value:
 80  	            param_dict[subproc_param].append(subproc_value)
 81  	    for param, values in param_dict.items():
 82  	        for value in values:
 83  	            if param:
(Pdb) n
> .../wooey/backend/utils.py(79)get_job_commands()
-> if subproc_value:
(Pdb) subproc_value
(Pdb) param._value
u'true'
(Pdb) param.value
True
(Pdb) param.get_subprocess_value()
{u'parameter': u'--my_optional_arg'}
```

**Comment by Chris7** [comment]
Good catch. I'll patch this now.

**Comment by hottwaj** [comment]
Looks like the fix should be the following in core.py (line marked "+"):

```
    def get_subprocess_value(self):
        value = self.value
        if self.value is None:
            return None
        field = self.parameter.form_field
        param = self.parameter.short_param
        com = {'parameter': param}
        if field == self.BOOLEAN:
            if value:
+              com['value'] = param
                return com
```

**Comment by hottwaj** [comment]
hmm actually my above fix isn't quite right... not as simple as that!

**Comment by Chris7** [comment]
I need to think about how to best do this. I don't want to confuse instances where value is a boolean and should be passed as a boolean. We need to check for when the parameter itself should be passed and the value is meaningless. I think checking for the boolean in get_job_commands is where it should occurr.

**Comment by Chris7** [comment]
I think it can work if we do 

if not values and param:
    com.append(param)

**Comment by hottwaj** [comment]
Are you talking about line 83?  If so param_dict doesn't have the '--optional_param' key in it there (because line 80 was not executed) for "--optional_param", so that won't quite do it...

Thanks for looking into so quickly though!  Have a good weekend, I'm now going to the pub :)

**Comment by Chris7** [comment]
It has it in it via line 77, it's just an empty list as its values.

**Comment by hottwaj** [comment]
Ah missed that, sorry!

**Comment by Chris7** [comment]
This has been fixed. Thanks for the report @hottwaj and the PR.

**Comment by hottwaj** [comment]
Cool, sorry for never getting around to the testing!

**Comment by CatherineH** [comment]
When will this be in the version in pip?

**Comment by Chris7** [comment]
@mfitzp  and I both are currently finishing up bits of our dissertation. After that we're going to set milestones for the next release. Or maybe just do a release of the current master and set milestones for the subsequent release. In anycase, real life caught up to both of us these past few months. I'll be free though soon so a new release in the next month may happen.

**Comment by hottwaj** [comment]
@CatherineH in case you didn't know already you can use pip to install straight from the most recent code changes on github using:
`pip install https://github.com/wooey/Wooey/archive/master.zip`

add `--upgrade` if you have a version of wooey installed already

**Comment by CatherineH** [comment]
Cool, thanks for the update! Good luck on your defenses!
