### ISSUE TITLE
Progress output / realtime updating

### ISSUE THREAD

**Issue by nzjrs** [wooey/Wooey#88]
This is a major regression from the previous version.

It would be good if a mechanism for progress reporting or real-time parsing of script output could be added.

This might require out of band capture of process stdout, and / or custom celery states

**Comment by Chris7** [comment]
This is something that is certainly going to be added back. 

We're going over ways to handle progress updates (like a regex you can define for each script that extracts its current state from its stdout/stderr), as well as the best way to monitor job updates (likely just watching for changes to the directory).

For the UI updates, we're considering how to best achieve this -- I'm in favor of a cache based system that minimizes interacting with the database. This will let us show things like file-previews for updated files and such without having to do a ton of writes every x seconds.

**Comment by mfitzp** [comment]
I'm working on this in #89

**Comment by nzjrs** [comment]
Great to hear. Let me know if I can help testing.

FWIW configurable regexes for progress reporting and detecting images/script output files would also be welcome.

**Comment by mfitzp** [comment]
@nzjrs the live output of stdout/stderr is working you can test it from the PR. Live updating the outputs (images, etc.) will be a little trickier but working on it.

**Comment by mmrasheed** [comment]
Hi,
I am looking for a solution where the terminal output on wooey page will be updated in real-time, at least the print command. Is it working now? Can you please provide an example python code to show this feature working?

I appreciate your help. :)

**Comment by Chris7** [comment]
It's a to-do feature. If I get some time this weekend, I'm going to take a look a #89 and see if I can complete it.

**Comment by Chris7** [comment]
@mmrasheed and @nzjrs This is currently in branch realtime-cache. I've tested it a bit, but if you'd like to check it out as well it would be appreciated. By default, it writes to the database but can make use of a cache with the WOOEY_REALTIME_CACHE setting, which should be set to the name of the cache you want to use for wooey. You cannot use a LocalMemCache for this and must use something like memcached or redis cache, as celery and django share different python processes and thus, do not share memory.

**Comment by Chris7** [comment]
Merged in with #89 and #126
