### ISSUE TITLE
python manage.py build_scripts unrecognized

### ISSUE THREAD

**Issue by CatherineH** [wooey/Wooey#9]
When running
```
python manage.py build_scripts
```
I get the error:

```
cholloway@nb-cholloway:~/Wooey$ python manage.py build_scripts
INFO:root:Processing file ./scripts/histogram_builder.py.
usage: manage.py [-h] [-f FILENAME] [-c COMPONENT] [-n UAV_NUMBER]
manage.py: error: unrecognized arguments: build_scripts
```
I get this on example scripts as well. I'm running Python 2.7.6.

**Comment by kobolddoido** [comment]
I got the same error here.
I installed wooey in other machine with an oldest version and this don't happens this problem.

**Comment by mfitzp** [comment]
The latest merged version of Wooey uses `python manage.py addscript` to add individual scripts to the database. Closing as this bug doesn't apply anymore, but thanks for reporting!
